'use strict';
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value);
const quantity = value => Math.min(999,Math.max(1,Math.floor(Number(value)||1)));
function read(key,fallback){try{const value=localStorage.getItem(key);return value===null?fallback:JSON.parse(value);}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{showToast('Your browser could not save changes. Keep this page open to retain your selection.');}}
function normalizeCart(value){const rows=new Map();if(!Array.isArray(value))return [];for(const item of value){if(!item||!products.some(p=>p.id===Number(item.id)&&p.stock!=='out')||!Number.isFinite(Number(item.qty))||Number(item.qty)<=0)continue;const id=Number(item.id);rows.set(id,quantity((rows.get(id)||0)+quantity(item.qty)));}return [...rows].map(([id,qty])=>({id,qty}));}
let cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',[])));
function loadFavorites(){const value=read('madhan_wishlist',read('yuvaraj_wishlist',[]));return Array.isArray(value)?[...new Set(value.map(Number))].filter(id=>products.some(p=>p.id===id)):[];}
let favorites=loadFavorites();
const categories=[...new Set(products.map(p=>p.category))];
const requested=new URLSearchParams(location.search).get('category');
const filters={category:categories.includes(requested)?requested:'All',search:'',sort:'default',availability:'all',max:5000,favorites:false};
let toastTimer;
function showToast(message){if(!$('toast'))return;$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function imageMarkup(p){return productImages[p.id]?`<img src="${escapeHTML(productImages[p.id])}" alt="${escapeHTML(p.name)}" loading="lazy" width="240" height="240">`:`<div class="product-placeholder" aria-label="Product photo unavailable"><b aria-hidden="true">✳</b><small>PHOTO COMING SOON</small></div>`;}
function qtyMarkup(p,value=1,cartMode=false){return `<div class="qty"><button type="button" data-action="${cartMode?'cart-step':'step'}" data-id="${p.id}" data-step="-1" aria-label="Decrease quantity of ${escapeHTML(p.name)}">−</button><input ${cartMode?'data-cart-qty':'data-product-qty'}="${p.id}" id="${cartMode?'cart-qty':'qty'}-${p.id}" type="number" min="1" max="999" step="1" value="${value}" aria-label="Quantity of ${escapeHTML(p.name)}"><button type="button" data-action="${cartMode?'cart-step':'step'}" data-id="${p.id}" data-step="1" aria-label="Increase quantity of ${escapeHTML(p.name)}">+</button></div>`;}
function favoriteButtonMarkup(p){const saved=favorites.includes(p.id);return `<button class="wish animated-heart${saved?' is-saved':''}" data-action="favorite" data-id="${p.id}" aria-label="${saved?'Remove '+escapeHTML(p.name)+' from saved':'Save '+escapeHTML(p.name)}" aria-pressed="${saved}" title="${saved?'Saved':'Save product'}"><span class="heart-shell" aria-hidden="true"><svg class="heart-outline" viewBox="0 0 24 24"><path d="M12 21s-7.2-4.35-9.45-8.56C.69 8.95 2.04 4.5 6.21 3.7 8.5 3.26 10.39 4.3 12 6.13c1.61-1.83 3.5-2.87 5.79-2.43 4.17.8 5.52 5.25 3.66 8.74C19.2 16.65 12 21 12 21Z"/></svg><svg class="heart-filled" viewBox="0 0 24 24"><path d="M12 21s-7.2-4.35-9.45-8.56C.69 8.95 2.04 4.5 6.21 3.7 8.5 3.26 10.39 4.3 12 6.13c1.61-1.83 3.5-2.87 5.79-2.43 4.17.8 5.52 5.25 3.66 8.74C19.2 16.65 12 21 12 21Z"/></svg><i></i><i></i><i></i><i></i><i></i><i></i></span></button>`;}
function card(p){const selected=cart.find(i=>i.id===p.id);return `<article class="product-card"><div class="product-visual"><span class="product-code">NO. ${String(p.number).padStart(2,'0')}</span><a href="product.html?id=${p.id}" aria-label="View ${escapeHTML(p.name)}">${imageMarkup(p)}</a>${favoriteButtonMarkup(p)}</div><div class="product-info"><p class="eyebrow">${escapeHTML(p.category)}</p><h3><a href="product.html?id=${p.id}">${escapeHTML(p.name)}</a></h3><div class="product-price"><strong>${p.stock==='pending'?'Rate pending':money(p.price)}</strong>${p.stock==='pending'?'':'<small>/ box</small>'}</div><div class="card-actions">${qtyMarkup(p)}<button class="button" data-action="add" data-id="${p.id}" ${p.stock==='out'?'disabled':''}>${p.stock==='out'?'Unavailable':selected?'Add more +':'Add to enquiry +'}</button></div><div class="selected-note${selected?' is-selected':''}" data-selected="${p.id}">${selected?`✓ ${selected.qty} in your enquiry`:'Choose a quantity to enquire'}</div><div class="product-card-links"><a href="product.html?id=${p.id}">View details ↗</a><a href="enquiry.html">Review enquiry</a></div></div></article>`;}
function filteredProducts(){let list=products.filter(p=>(filters.category==='All'||p.category===filters.category)&&(!filters.search||(p.name+' '+p.category).toLowerCase().includes(filters.search))&&(filters.availability==='all'||p.stock===filters.availability)&&(!filters.favorites||favorites.includes(p.id))&&(p.stock==='pending'||p.price<=filters.max));if(filters.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(filters.sort.startsWith('price'))list.sort((a,b)=>{if(a.stock==='pending'||b.stock==='pending')return Number(a.stock==='pending')-Number(b.stock==='pending');return filters.sort==='price-low'?a.price-b.price:b.price-a.price;});return list;}
function renderCategories(){if(!$('categoryButtons'))return;$('categoryButtons').innerHTML=['All',...categories].map(c=>`<button class="category-button" data-category="${escapeHTML(c)}" aria-pressed="${filters.category===c}"><span>${c==='All'?'All products':escapeHTML(c)}</span><span>${c==='All'?products.length:products.filter(p=>p.category===c).length}</span></button>`).join('');}
function renderProducts(){if(!$('productGrid'))return;const list=filteredProducts();$('resultCount').textContent=`${list.length} of ${products.length} products`;$('productGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><h2>No matches this time.</h2><p>Try another search or clear your filters.</p><button class="button" data-action="reset">Reset filters</button></div>';updateFavorites();}
function updateFavorites(){if($('favoriteCount'))$('favoriteCount').textContent=favorites.length;if($('favoritesToggle'))$('favoritesToggle').setAttribute('aria-pressed',String(filters.favorites));document.querySelectorAll('[data-action="favorite"]').forEach(button=>{const saved=favorites.includes(Number(button.dataset.id));button.classList.toggle('is-saved',saved);button.setAttribute('aria-pressed',String(saved));const p=products.find(p=>p.id===Number(button.dataset.id));button.setAttribute('aria-label',saved?`Remove ${p?.name||'product'} from saved`:`Save ${p?.name||'product'}`);if(button.classList.contains('cart-icon-action'))button.textContent=saved?'♥ Saved':'♡ Save';});}
function resetFilters(){Object.assign(filters,{category:'All',search:'',sort:'default',availability:'all',max:5000,favorites:false});if($('searchInput'))$('searchInput').value='';if($('sortSelect'))$('sortSelect').value='default';if($('availabilityFilter'))$('availabilityFilter').value='all';if($('priceRange'))$('priceRange').value=5000;if($('priceValue'))$('priceValue').textContent=money(5000);if($('productGrid')){history.replaceState(null,'',location.pathname);renderCategories();renderProducts();}}
function totals(){return cart.reduce((sum,item)=>{const p=products.find(p=>p.id===item.id);if(p){sum.qty+=item.qty;sum.items+=1;if(p.stock==='pending'){sum.pending=true;sum.pendingItems+=1;}else sum.total+=p.price*item.qty;}return sum;},{qty:0,items:0,total:0,pending:false,pendingItems:0});}
let cartView={search:'',sort:'added'};
function cartDisplayItems(){let list=cart.map((item,index)=>({item,index,p:products.find(p=>p.id===item.id)})).filter(row=>row.p);if(cartView.search){const q=cartView.search.toLowerCase();list=list.filter(({p})=>(p.name+' '+p.category+' '+p.number).toLowerCase().includes(q));}if(cartView.sort==='name')list.sort((a,b)=>a.p.name.localeCompare(b.p.name));if(cartView.sort==='category')list.sort((a,b)=>a.p.category.localeCompare(b.p.category)||a.p.name.localeCompare(b.p.name));if(cartView.sort==='price-high'||cartView.sort==='price-low')list.sort((a,b)=>{const av=a.p.stock==='pending'?-1:a.p.price*a.item.qty,bv=b.p.stock==='pending'?-1:b.p.price*b.item.qty;return cartView.sort==='price-high'?bv-av:av-bv;});return list;}
function cartText(){const t=totals();const lines=cart.map((item,index)=>{const p=products.find(p=>p.id===item.id);return `${index+1}. ${p.name} | ${p.category} | Qty ${item.qty} | ${p.stock==='pending'?'Rate pending':money(p.price*item.qty)}`;});return `Madhan Crackers - Product Enquiry\n${lines.join('\n')}\n\n${t.items} products | ${t.qty} boxes\nEstimated total: ${money(t.total)}${t.pending?' + pending rates':''}`;}
function downloadCartCSV(){if(!cart.length){showToast('Add products before exporting.');return;}const rows=[['No','Product','Category','Catalogue No','Rate / box','Qty','Amount']];cart.forEach((item,index)=>{const p=products.find(p=>p.id===item.id);rows.push([index+1,p.name,p.category,p.number,p.stock==='pending'?'Pending':p.price,item.qty,p.stock==='pending'?'Pending':(p.price*item.qty).toFixed(2)]);});const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='madhan-crackers-enquiry.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);showToast('Cart CSV downloaded.');}
function quickCartWhatsApp(){if(!cart.length){showToast('Add products before opening WhatsApp.');return;}window.open(whatsappURL('Hello '+BUSINESS_CONFIG.name+', I would like to enquire about these products:\n\n'+cartText()+'\n\nPlease confirm stock and final rates.'),'_blank','noopener,noreferrer');}
function addSavedProductsToCart(){let added=0;for(const id of favorites){const p=products.find(p=>p.id===id&&p.stock!=='out');if(p&&!cart.some(i=>i.id===id)){cart.push({id,qty:1});added++;}}if(added){saveCart();showToast(`${added} saved ${added===1?'product':'products'} added to your enquiry.`);}else showToast(favorites.length?'All saved products are already in your enquiry.':'Save products first to add them here.');}
async function shareCartSelection(){if(!cart.length){showToast('Add products before sharing.');return;}const text=cartText();try{if(navigator.share){await navigator.share({title:'Madhan Crackers enquiry',text});}else await copyText(text);}catch(error){if(error?.name!=='AbortError')await copyText(text);}}
function saveCart(){save('madhan_cart',cart);updateCart();}
function updateCart(){
 const t=totals();
 if($('cartCount'))$('cartCount').textContent=t.qty;
 document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=t.qty);
 document.querySelectorAll('[data-selected]').forEach(el=>{const item=cart.find(i=>i.id===Number(el.dataset.selected));el.textContent=item?`✓ ${item.qty} in your enquiry`:'Choose a quantity to enquire';el.classList.toggle('is-selected',Boolean(item));});
 document.querySelectorAll('[data-action="add"]').forEach(button=>{const id=Number(button.dataset.id),p=products.find(p=>p.id===id),item=cart.find(i=>i.id===id);if(p&&p.stock!=='out')button.textContent=item?'Add more +':'Add to enquiry +';});
 if($('cartUniqueCount'))$('cartUniqueCount').textContent=`${t.items} ${t.items===1?'item':'items'}`;
 if($('cartItems')){
   const focus=document.activeElement;
   const focusedId=focus?.hasAttribute('data-cart-qty')?focus.id:null;
   const rows=cartDisplayItems();
   $('cartItems').innerHTML=cart.length?(rows.length?rows.map(({item,p})=>`<article class="cart-row cart-row-rich">
     <a class="cart-thumb" href="product.html?id=${p.id}" aria-label="View ${escapeHTML(p.name)}">${imageMarkup(p)}</a>
     <div class="cart-product-main">
       <div class="cart-title-line"><div><p class="cart-category">${escapeHTML(p.category)} · NO. ${String(p.number).padStart(2,'0')}</p><h3><a href="product.html?id=${p.id}">${escapeHTML(p.name)}</a></h3></div><span class="stock-chip ${p.stock}">${p.stock==='pending'?'Rate pending':'Available'}</span></div>
       <div class="cart-rate-line"><span>${p.stock==='pending'?'Price will be confirmed':money(p.price)+' / box'}</span><span>Unit: ${escapeHTML(p.unit)}</span></div>
       <div class="cart-row-controls">${qtyMarkup(p,item.qty,true)}<button class="cart-icon-action ${favorites.includes(p.id)?'saved':''}" data-action="favorite" data-id="${p.id}" aria-label="${favorites.includes(p.id)?'Remove from saved':'Save product'}">${favorites.includes(p.id)?'♥ Saved':'♡ Save'}</button><a class="cart-icon-action" href="product.html?id=${p.id}">View ↗</a><button class="cart-icon-action danger" data-action="remove" data-id="${p.id}">Remove</button></div>
     </div>
     <div class="cart-row-end"><small>Line total</small><strong>${p.stock==='pending'?'Pending':money(p.price*item.qty)}</strong><button class="cart-plus-one" data-action="cart-step" data-step="1" data-id="${p.id}" aria-label="Add one more ${escapeHTML(p.name)}">+1 box</button></div>
   </article>`).join(''):'<div class="cart-no-match"><strong>No selected product matches this search.</strong><button type="button" class="text-link" id="clearCartSearchInline">Clear cart search</button></div>'):'<div class="empty"><h3>Your celebration starts here.</h3><p>Choose a few products to build your enquiry.</p><div class="empty-actions"><a href="catalogue.html" class="button">Explore the collection ↗</a><a href="renga%202026.pdf" target="_blank" rel="noopener" class="outline">View Price List PDF</a></div></div>';
   $('cartSummary').innerHTML=`<div class="cart-summary-grid"><div><span>Products</span><strong>${t.items}</strong></div><div><span>Total boxes</span><strong>${t.qty}</strong></div><div><span>Pending rates</span><strong>${t.pendingItems}</strong></div></div><div class="summary-row total"><span>Estimated total</span><strong>${money(t.total)}</strong></div><div class="cart-summary-actions"><a class="outline" href="renga%202026.pdf" target="_blank" rel="noopener"><b>PDF</b> View price list</a><button type="button" class="button" id="summaryContinue">Enter details ↓</button></div><p class="fine-print">${t.pending?'Excludes products with pending rates. ':''}Final stock, prices and delivery charges will be confirmed by our team.</p>`;
   if($('clearCart'))$('clearCart').hidden=!cart.length;
   if($('addSavedToCart'))$('addSavedToCart').disabled=!favorites.length;
   if($('copyCartList'))$('copyCartList').disabled=!cart.length;
   if($('shareCartList'))$('shareCartList').disabled=!cart.length;
   if(focusedId)$(focusedId)?.focus();
 }
 if($('collectionCartStrip')){
   $('collectionCartStrip').classList.toggle('has-selection',t.items>0);
   if($('collectionCartTitle'))$('collectionCartTitle').textContent=t.items?`${t.items} ${t.items===1?'product':'products'} selected`:'Start selecting products';
   if($('collectionCartMeta'))$('collectionCartMeta').textContent=t.items?`${t.qty} ${t.qty===1?'box':'boxes'} in your enquiry${favorites.length?` · ${favorites.length} saved`:''}`:'Choose quantities and add products while you browse.';
   if($('collectionCartTotal'))$('collectionCartTotal').textContent=money(t.total);
   if($('collectionPendingMeta'))$('collectionPendingMeta').textContent=t.pending?`${t.pendingItems} pending ${t.pendingItems===1?'rate':'rates'} · final total confirmed later`:'Catalogue estimate · final stock/rates confirmed later';
   if($('collectionCartBadge'))$('collectionCartBadge').textContent=t.qty;
   ['collectionWhatsApp','collectionCopy','collectionShare','collectionClear'].forEach(id=>{if($(id))$(id).disabled=!cart.length;});
   if($('collectionAddSaved'))$('collectionAddSaved').disabled=!favorites.length;
 }
 if($('paymentEstimate'))$('paymentEstimate').textContent=`Enquiry estimate: ${money(t.total)}${t.pending?' + pending rates':''}. Enter the final amount agreed with our team.`;
}
function renderDetail(){if(!$('productDetail'))return;const id=Number(new URLSearchParams(location.search).get('id'));const p=products.find(p=>p.id===id);if(!p){$('productDetail').innerHTML='<div class="empty"><h1>Product not found.</h1><p>This link doesn’t match an item in our collection.</p><a class="button" href="catalogue.html">Browse all products</a></div>';return;}document.title=p.name+' | Madhan Crackers';$('productDetail').innerHTML=`<div class="detail-grid"><div class="product-visual">${imageMarkup(p)}</div><div><p class="eyebrow">${escapeHTML(p.category)} / NO. ${p.number}</p><h1>${escapeHTML(p.name)}</h1><div class="product-price"><strong>${p.stock==='pending'?'Rate pending':money(p.price)}</strong><small>/ box</small></div><p class="muted">Add this item to your celebration. Our team will confirm availability, final pricing and delivery when you send your enquiry.</p><div class="card-actions">${qtyMarkup(p)}<button class="button" data-action="add" data-id="${p.id}" ${p.stock==='out'?'disabled':''}>Add to enquiry +</button></div><p class="selected-note" data-selected="${p.id}"></p><a class="text-link" href="enquiry.html">Review your enquiry ↗</a><div class="detail-meta"><span>Unit: ${escapeHTML(p.unit)}</span><span>${p.stock==='pending'?'Price to be confirmed':p.stock==='out'?'Out of stock':'Catalogue rate listed'}</span></div></div></div>`;}
function customer(){return Object.fromEntries(['Name','Phone','Email','Address','Notes'].map(key=>[key.toLowerCase(),$('customer'+key)?.value.trim()||'']));}
function validateCustomer(){if(!cart.length){$('formError').textContent='Please add at least one product to your enquiry.';showToast('Add products before preparing your enquiry.');return false;}if(!$('customerForm').reportValidity())return false;$('formError').textContent='';return true;}
function reference(){return 'MC-'+new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);}
function enquiryMessage(c,ref){const t=totals();return `Hello ${BUSINESS_CONFIG.name}, I would like to make an enquiry.\nReference: ${ref}\nName: ${c.name}\nMobile: ${c.phone}\n${c.email?'Email: '+c.email+'\n':''}Address: ${c.address}\n${c.notes?'Notes: '+c.notes+'\n':''}\n`+cart.map((item,index)=>{const p=products.find(p=>p.id===item.id);return `${index+1}. ${p.name} × ${item.qty} — ${p.stock==='pending'?'Rate pending':money(p.price*item.qty)}`;}).join('\n')+`\n\nEstimated total: ${money(t.total)}${t.pending?' + pending rates':''}.\nPlease confirm final stock, rates and delivery.`;}
function whatsappURL(message){return 'https://wa.me/'+BUSINESS_CONFIG.whatsapp.replace(/\D/g,'')+'?text='+encodeURIComponent(message);}
function printEnquiry(){if(!validateCustomer())return;const c=customer(),t=totals();$('printSheet').innerHTML=`<h1>Madhan Crackers</h1><p>${escapeHTML(BUSINESS_CONFIG.address)} | ${escapeHTML(BUSINESS_CONFIG.phone)}</p><h2>Customer enquiry · ${reference()}</h2><p>${escapeHTML(c.name)} · ${escapeHTML(c.phone)}${c.email?' · '+escapeHTML(c.email):''}</p><p>${escapeHTML(c.address)}</p><table><thead><tr><th>#</th><th>Product</th><th>Rate / box</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${cart.map((item,index)=>{const p=products.find(p=>p.id===item.id);return `<tr><td>${index+1}</td><td>${escapeHTML(p.name)}</td><td>${p.stock==='pending'?'Pending':money(p.price)}</td><td>${item.qty}</td><td>${p.stock==='pending'?'Pending':money(p.price*item.qty)}</td></tr>`;}).join('')}</tbody></table><div class="print-total"><h2>Estimated total: ${money(t.total)}${t.pending?' + pending rates':''}</h2><p>${escapeHTML(c.notes)}</p><small>Please confirm final stock, rates and delivery before payment.</small></div>`;window.print();}
async function copyText(value){try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(value);showToast('Copied to clipboard.');}catch{showToast('Copy is unavailable here. Select and copy the displayed details.');}}
function setTheme(dark){document.body.classList.toggle('dark',dark);$('themeToggle').setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');$('themeToggle').setAttribute('aria-pressed',String(dark));}
function closeMenu(){$('navigation').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action],[data-category]');if(button){const id=Number(button.dataset.id),action=button.dataset.action;if(button.hasAttribute('data-category')){filters.category=button.dataset.category;const url=new URL(location.href);filters.category==='All'?url.searchParams.delete('category'):url.searchParams.set('category',filters.category);history.replaceState(null,'',url);renderCategories();renderProducts();}if(action==='reset')resetFilters();if(action==='favorite'){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('madhan_wishlist',favorites);if(filters.favorites)renderProducts();updateFavorites();updateCart();}if(action==='step'){const input=$('qty-'+id);input.value=quantity(Number(input.value)+Number(button.dataset.step));}if(action==='add'){const p=products.find(p=>p.id===id);if(!p||p.stock==='out')return;const qty=quantity($('qty-'+id)?.value);const item=cart.find(i=>i.id===id);if(item)item.qty=quantity(item.qty+qty);else cart.push({id,qty});saveCart();showToast(p.name+' added to your enquiry.');}if(action==='cart-step'){const item=cart.find(i=>i.id===id);if(item){item.qty=quantity(item.qty+Number(button.dataset.step));saveCart();}}if(action==='remove'){cart=cart.filter(i=>i.id!==id);saveCart();showToast('Product removed from your enquiry.');}}
if(!$('navigation').contains(event.target)&&!$('menuToggle').contains(event.target))closeMenu();});
document.addEventListener('change',event=>{const el=event.target;if(el.hasAttribute('data-product-qty'))el.value=quantity(el.value);if(el.hasAttribute('data-cart-qty')){const item=cart.find(i=>i.id===Number(el.dataset.cartQty));if(item){item.qty=quantity(el.value);saveCart();}}});
$('year').textContent=new Date().getFullYear();
setTheme(read('madhan_dark',false));
$('themeToggle').addEventListener('click',()=>{const dark=!document.body.classList.contains('dark');setTheme(dark);save('madhan_dark',dark);});
$('menuToggle').addEventListener('click',()=>{const open=$('navigation').classList.toggle('open');$('menuToggle').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();}if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable&&$('searchInput')){event.preventDefault();$('searchInput').focus();}});
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=whatsappURL(a.dataset.wa||'Hello Madhan Crackers, I have an enquiry.');a.target='_blank';a.rel='noopener noreferrer';});
if($('featuredGrid'))$('featuredGrid').innerHTML=[9,34,42,69].map(id=>products.find(p=>p.id===id)).filter(Boolean).map(card).join('');
renderCategories();renderProducts();renderDetail();updateCart();updateFavorites();
$('searchInput')?.addEventListener('input',event=>{filters.search=event.target.value.trim().toLowerCase();renderProducts();});
$('sortSelect')?.addEventListener('change',event=>{filters.sort=event.target.value;renderProducts();});
$('availabilityFilter')?.addEventListener('change',event=>{filters.availability=event.target.value;renderProducts();});
$('priceRange')?.addEventListener('input',event=>{filters.max=Number(event.target.value);$('priceValue').textContent=money(filters.max);renderProducts();});
$('favoritesToggle')?.addEventListener('click',()=>{filters.favorites=!filters.favorites;renderProducts();});
$('resetFilters')?.addEventListener('click',resetFilters);
$('clearCart')?.addEventListener('click',()=>{if(cart.length&&confirm('Clear all products from your enquiry?')){cart=[];saveCart();}});
$('cartSearch')?.addEventListener('input',event=>{cartView.search=event.target.value.trim();updateCart();});
$('cartSort')?.addEventListener('change',event=>{cartView.sort=event.target.value;updateCart();});
$('addSavedToCart')?.addEventListener('click',addSavedProductsToCart);
$('copyCartList')?.addEventListener('click',()=>cart.length&&copyText(cartText()));
$('shareCartList')?.addEventListener('click',shareCartSelection);
$('downloadCartCsv')?.addEventListener('click',downloadCartCSV);
$('quickCartWhatsApp')?.addEventListener('click',quickCartWhatsApp);
$('collectionAddSaved')?.addEventListener('click',addSavedProductsToCart);
$('collectionCopy')?.addEventListener('click',()=>cart.length?copyText(cartText()):showToast('Add products before copying.'));
$('collectionShare')?.addEventListener('click',shareCartSelection);
$('collectionWhatsApp')?.addEventListener('click',quickCartWhatsApp);
$('collectionClear')?.addEventListener('click',()=>{if(cart.length&&confirm('Clear all selected products?')){cart=[];saveCart();showToast('Your selection has been cleared.');}});
document.addEventListener('click',event=>{if(event.target?.id==='summaryContinue'||event.target?.id==='continueEnquiry'){$('customerForm')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('customerName')?.focus({preventScroll:true}),450);}if(event.target?.id==='clearCartSearchInline'){cartView.search='';if($('cartSearch'))$('cartSearch').value='';updateCart();}});
$('customerForm')?.addEventListener('submit',event=>{event.preventDefault();if(!validateCustomer())return;window.open(whatsappURL(enquiryMessage(customer(),reference())),'_blank','noopener,noreferrer');});
$('printEnquiry')?.addEventListener('click',printEnquiry);
window.addEventListener('storage',event=>{if(event.key==='madhan_cart'||event.key===null){cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',[])));updateCart();}if(event.key==='madhan_wishlist'||event.key===null){favorites=loadFavorites();renderProducts();updateFavorites();}if(event.key==='madhan_dark'||event.key===null)setTheme(read('madhan_dark',false));});
window.addEventListener('pageshow',()=>{cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',cart)));updateCart();});
const currentPage = location.pathname.split('/').pop() || 'index.html';
document.querySelectorAll('#navigation a,.mobile-dock a').forEach(link=>{
  const match=link.getAttribute('href')===(currentPage==='product.html'?'catalogue.html':currentPage);
  if(match)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');
});
