'use strict';
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value);
const quantity = value => Math.min(999,Math.max(1,Math.floor(Number(value)||1)));
function read(key,fallback){try{const value=localStorage.getItem(key);return value===null?fallback:JSON.parse(value);}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{showToast('Your browser could not save changes. Keep this page open to retain your selection.');}}
function normalizeCart(value){const rows=new Map();if(!Array.isArray(value))return [];for(const item of value){if(!item||!products.some(p=>p.id===Number(item.id)&&p.stock!=='out')||!Number.isFinite(Number(item.qty))||Number(item.qty)<=0)continue;const id=Number(item.id);rows.set(id,quantity((rows.get(id)||0)+quantity(item.qty)));}return [...rows].map(([id,qty])=>({id,qty}));}
let cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',[])));
function loadFavorites(){const value=read('madhan_wishlist',read('yuvaraj_wishlist',[]));return Array.isArray(value)?[...new Set(value.map(Number))].filter(id=>products.some(p=>p.id===id)):[];}
let favorites=loadFavorites();
const categories=[...new Set(products.map(p=>p.category))];
const requested=new URLSearchParams(location.search).get('category');
const filters={category:categories.includes(requested)?requested:'All',search:'',sort:'default',availability:'all',max:5000,favorites:false};
let toastTimer;
function showToast(message){if(!$('toast'))return;$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function imageMarkup(p){return productImages[p.id]?`<img src="${escapeHTML(productImages[p.id])}" alt="${escapeHTML(p.name)}" loading="lazy" width="240" height="240">`:`<div class="product-placeholder" aria-label="Product photo unavailable"><b aria-hidden="true">✳</b><small>PHOTO COMING SOON</small></div>`;}
function qtyMarkup(p,value=1,cartMode=false){return `<div class="qty"><button type="button" data-action="${cartMode?'cart-step':'step'}" data-id="${p.id}" data-step="-1" aria-label="Decrease quantity of ${escapeHTML(p.name)}">−</button><input ${cartMode?'data-cart-qty':'data-product-qty'}="${p.id}" id="${cartMode?'cart-qty':'qty'}-${p.id}" type="number" min="1" max="999" step="1" value="${value}" aria-label="Quantity of ${escapeHTML(p.name)}"><button type="button" data-action="${cartMode?'cart-step':'step'}" data-id="${p.id}" data-step="1" aria-label="Increase quantity of ${escapeHTML(p.name)}">+</button></div>`;}
function card(p){const selected=cart.find(i=>i.id===p.id);return `<article class="product-card"><div class="product-visual"><span class="product-code">NO. ${String(p.number).padStart(2,'0')}</span><a href="product.html?id=${p.id}" aria-label="View ${escapeHTML(p.name)}">${imageMarkup(p)}</a><button class="wish" data-action="favorite" data-id="${p.id}" aria-label="Save ${escapeHTML(p.name)}" aria-pressed="${favorites.includes(p.id)}">${favorites.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><p class="eyebrow">${escapeHTML(p.category)}</p><h3><a href="product.html?id=${p.id}">${escapeHTML(p.name)}</a></h3><div class="product-price"><strong>${p.stock==='pending'?'Rate pending':money(p.price)}</strong>${p.stock==='pending'?'':'<small>/ box</small>'}</div><div class="card-actions">${qtyMarkup(p)}<button class="button" data-action="add" data-id="${p.id}" ${p.stock==='out'?'disabled':''}>${p.stock==='out'?'Unavailable':'+ Add'}</button></div><div class="selected-note" data-selected="${p.id}">${selected?`${selected.qty} in your enquiry`:'Choose a quantity to enquire'}</div></div></article>`;}
function filteredProducts(){let list=products.filter(p=>(filters.category==='All'||p.category===filters.category)&&(!filters.search||(p.name+' '+p.category).toLowerCase().includes(filters.search))&&(filters.availability==='all'||p.stock===filters.availability)&&(!filters.favorites||favorites.includes(p.id))&&(p.stock==='pending'||p.price<=filters.max));if(filters.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(filters.sort.startsWith('price'))list.sort((a,b)=>{if(a.stock==='pending'||b.stock==='pending')return Number(a.stock==='pending')-Number(b.stock==='pending');return filters.sort==='price-low'?a.price-b.price:b.price-a.price;});return list;}
function renderCategories(){if(!$('categoryButtons'))return;$('categoryButtons').innerHTML=['All',...categories].map(c=>`<button class="category-button" data-category="${escapeHTML(c)}" aria-pressed="${filters.category===c}"><span>${c==='All'?'All products':escapeHTML(c)}</span><span>${c==='All'?products.length:products.filter(p=>p.category===c).length}</span></button>`).join('');}
function renderProducts(){if(!$('productGrid'))return;const list=filteredProducts();$('resultCount').textContent=`${list.length} of ${products.length} products`;$('productGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><h2>No matches this time.</h2><p>Try another search or clear your filters.</p><button class="button" data-action="reset">Reset filters</button></div>';updateFavorites();}
function updateFavorites(){if($('favoriteCount'))$('favoriteCount').textContent=favorites.length;if($('favoritesToggle'))$('favoritesToggle').setAttribute('aria-pressed',String(filters.favorites));document.querySelectorAll('[data-action="favorite"]').forEach(button=>{const saved=favorites.includes(Number(button.dataset.id));button.textContent=saved?'♥':'♡';button.setAttribute('aria-pressed',String(saved));});}
function resetFilters(){Object.assign(filters,{category:'All',search:'',sort:'default',availability:'all',max:5000,favorites:false});if($('searchInput'))$('searchInput').value='';if($('sortSelect'))$('sortSelect').value='default';if($('availabilityFilter'))$('availabilityFilter').value='all';if($('priceRange'))$('priceRange').value=5000;if($('priceValue'))$('priceValue').textContent=money(5000);if($('productGrid')){history.replaceState(null,'',location.pathname);renderCategories();renderProducts();}}
function totals(){return cart.reduce((sum,item)=>{const p=products.find(p=>p.id===item.id);if(p){sum.qty+=item.qty;if(p.stock==='pending')sum.pending=true;else sum.total+=p.price*item.qty;}return sum;},{qty:0,total:0,pending:false});}
function saveCart(){save('madhan_cart',cart);updateCart();}
function updateCart(){const t=totals();$('cartCount').textContent=t.qty;document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=t.qty);document.querySelectorAll('[data-selected]').forEach(el=>{const item=cart.find(i=>i.id===Number(el.dataset.selected));el.textContent=item?`${item.qty} in your enquiry`:'Choose a quantity to enquire';});if($('cartItems')){const focus=document.activeElement;const focusedId=focus?.hasAttribute('data-cart-qty')?focus.id:null;$('cartItems').innerHTML=cart.length?cart.map(item=>{const p=products.find(p=>p.id===item.id);return `<article class="cart-row">${imageMarkup(p)}<div><h3><a href="product.html?id=${p.id}">${escapeHTML(p.name)}</a></h3><small>${p.stock==='pending'?'Rate pending':money(p.price)+' / box'}</small>${qtyMarkup(p,item.qty,true)}</div><div class="cart-row-end"><strong>${p.stock==='pending'?'Pending':money(p.price*item.qty)}</strong><button class="text-link danger" data-action="remove" data-id="${p.id}">Remove</button></div></article>`;}).join(''):'<div class="empty"><h3>Your celebration starts here.</h3><p>Choose a few products to build your enquiry.</p><a href="catalogue.html" class="button">Explore the collection ↗</a></div>';$('cartSummary').innerHTML=`<div class="summary-row"><span>Total quantity</span><strong>${t.qty} boxes</strong></div><div class="summary-row total"><span>Estimated total</span><strong>${money(t.total)}</strong></div><p class="fine-print">${t.pending?'Excludes products with pending rates. ':''}Final stock, prices and delivery charges will be confirmed by our team.</p>`;$('clearCart').hidden=!cart.length;if(focusedId)$(focusedId)?.focus();}if($('paymentEstimate'))$('paymentEstimate').textContent=`Enquiry estimate: ${money(t.total)}${t.pending?' + pending rates':''}. Enter the final amount agreed with our team.`;}
function renderDetail(){if(!$('productDetail'))return;const id=Number(new URLSearchParams(location.search).get('id'));const p=products.find(p=>p.id===id);if(!p){$('productDetail').innerHTML='<div class="empty"><h1>Product not found.</h1><p>This link doesn’t match an item in our collection.</p><a class="button" href="catalogue.html">Browse all products</a></div>';return;}document.title=p.name+' | Madhan Crackers';$('productDetail').innerHTML=`<div class="detail-grid"><div class="product-visual">${imageMarkup(p)}</div><div><p class="eyebrow">${escapeHTML(p.category)} / NO. ${p.number}</p><h1>${escapeHTML(p.name)}</h1><div class="product-price"><strong>${p.stock==='pending'?'Rate pending':money(p.price)}</strong><small>/ box</small></div><p class="muted">Add this item to your celebration. Our team will confirm availability, final pricing and delivery when you send your enquiry.</p><div class="card-actions">${qtyMarkup(p)}<button class="button" data-action="add" data-id="${p.id}" ${p.stock==='out'?'disabled':''}>Add to enquiry +</button></div><p class="selected-note" data-selected="${p.id}"></p><a class="text-link" href="enquiry.html">Review your enquiry ↗</a><div class="detail-meta"><span>Unit: ${escapeHTML(p.unit)}</span><span>${p.stock==='pending'?'Price to be confirmed':p.stock==='out'?'Out of stock':'Catalogue rate listed'}</span></div></div></div>`;}
function customer(){return Object.fromEntries(['Name','Phone','Email','Address','Notes'].map(key=>[key.toLowerCase(),$('customer'+key)?.value.trim()||'']));}
function validateCustomer(){if(!cart.length){$('formError').textContent='Please add at least one product to your enquiry.';showToast('Add products before preparing your enquiry.');return false;}if(!$('customerForm').reportValidity())return false;$('formError').textContent='';return true;}
function reference(){return 'MC-'+new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);}
function enquiryMessage(c,ref){const t=totals();return `Hello ${BUSINESS_CONFIG.name}, I would like to make an enquiry.\nReference: ${ref}\nName: ${c.name}\nMobile: ${c.phone}\n${c.email?'Email: '+c.email+'\n':''}Address: ${c.address}\n${c.notes?'Notes: '+c.notes+'\n':''}\n`+cart.map((item,index)=>{const p=products.find(p=>p.id===item.id);return `${index+1}. ${p.name} × ${item.qty} — ${p.stock==='pending'?'Rate pending':money(p.price*item.qty)}`;}).join('\n')+`\n\nEstimated total: ${money(t.total)}${t.pending?' + pending rates':''}.\nPlease confirm final stock, rates and delivery.`;}
function whatsappURL(message){return 'https://wa.me/'+BUSINESS_CONFIG.whatsapp.replace(/\D/g,'')+'?text='+encodeURIComponent(message);}
function printEnquiry(){if(!validateCustomer())return;const c=customer(),t=totals();$('printSheet').innerHTML=`<h1>Madhan Crackers</h1><p>${escapeHTML(BUSINESS_CONFIG.address)} | ${escapeHTML(BUSINESS_CONFIG.phone)}</p><h2>Customer enquiry · ${reference()}</h2><p>${escapeHTML(c.name)} · ${escapeHTML(c.phone)}${c.email?' · '+escapeHTML(c.email):''}</p><p>${escapeHTML(c.address)}</p><table><thead><tr><th>#</th><th>Product</th><th>Rate / box</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${cart.map((item,index)=>{const p=products.find(p=>p.id===item.id);return `<tr><td>${index+1}</td><td>${escapeHTML(p.name)}</td><td>${p.stock==='pending'?'Pending':money(p.price)}</td><td>${item.qty}</td><td>${p.stock==='pending'?'Pending':money(p.price*item.qty)}</td></tr>`;}).join('')}</tbody></table><div class="print-total"><h2>Estimated total: ${money(t.total)}${t.pending?' + pending rates':''}</h2><p>${escapeHTML(c.notes)}</p><small>Please confirm final stock, rates and delivery before payment.</small></div>`;window.print();}
async function copyText(value){try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(value);showToast('Copied to clipboard.');}catch{showToast('Copy is unavailable here. Select and copy the displayed details.');}}
function setTheme(dark){document.body.classList.toggle('dark',dark);$('themeToggle').setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');$('themeToggle').setAttribute('aria-pressed',String(dark));}
function closeMenu(){$('navigation').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');}
document.addEventListener('click',event=>{const button=event.target.closest('[data-action],[data-category]');if(button){const id=Number(button.dataset.id),action=button.dataset.action;if(button.hasAttribute('data-category')){filters.category=button.dataset.category;const url=new URL(location.href);filters.category==='All'?url.searchParams.delete('category'):url.searchParams.set('category',filters.category);history.replaceState(null,'',url);renderCategories();renderProducts();}if(action==='reset')resetFilters();if(action==='favorite'){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('madhan_wishlist',favorites);if(filters.favorites)renderProducts();updateFavorites();}if(action==='step'){const input=$('qty-'+id);input.value=quantity(Number(input.value)+Number(button.dataset.step));}if(action==='add'){const p=products.find(p=>p.id===id);if(!p||p.stock==='out')return;const qty=quantity($('qty-'+id)?.value);const item=cart.find(i=>i.id===id);if(item)item.qty=quantity(item.qty+qty);else cart.push({id,qty});saveCart();showToast(p.name+' added to your enquiry.');}if(action==='cart-step'){const item=cart.find(i=>i.id===id);if(item){item.qty=quantity(item.qty+Number(button.dataset.step));saveCart();}}if(action==='remove'){cart=cart.filter(i=>i.id!==id);saveCart();showToast('Product removed from your enquiry.');}}
if(!$('navigation').contains(event.target)&&!$('menuToggle').contains(event.target))closeMenu();});
document.addEventListener('change',event=>{const el=event.target;if(el.hasAttribute('data-product-qty'))el.value=quantity(el.value);if(el.hasAttribute('data-cart-qty')){const item=cart.find(i=>i.id===Number(el.dataset.cartQty));if(item){item.qty=quantity(el.value);saveCart();}}});
$('year').textContent=new Date().getFullYear();
setTheme(read('madhan_dark',false));
$('themeToggle').addEventListener('click',()=>{const dark=!document.body.classList.contains('dark');setTheme(dark);save('madhan_dark',dark);});
$('menuToggle').addEventListener('click',()=>{const open=$('navigation').classList.toggle('open');$('menuToggle').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();}if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable&&$('searchInput')){event.preventDefault();$('searchInput').focus();}});
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=whatsappURL(a.dataset.wa||'Hello Madhan Crackers, I have an enquiry.');a.target='_blank';a.rel='noopener noreferrer';});
if($('featuredGrid'))$('featuredGrid').innerHTML=[9,34,42,69].map(id=>products.find(p=>p.id===id)).filter(Boolean).map(card).join('');
renderCategories();renderProducts();renderDetail();updateCart();updateFavorites();
$('searchInput')?.addEventListener('input',event=>{filters.search=event.target.value.trim().toLowerCase();renderProducts();});
$('sortSelect')?.addEventListener('change',event=>{filters.sort=event.target.value;renderProducts();});
$('availabilityFilter')?.addEventListener('change',event=>{filters.availability=event.target.value;renderProducts();});
$('priceRange')?.addEventListener('input',event=>{filters.max=Number(event.target.value);$('priceValue').textContent=money(filters.max);renderProducts();});
$('favoritesToggle')?.addEventListener('click',()=>{filters.favorites=!filters.favorites;renderProducts();});
$('resetFilters')?.addEventListener('click',resetFilters);
$('clearCart')?.addEventListener('click',()=>{if(cart.length&&confirm('Clear all products from your enquiry?')){cart=[];saveCart();}});
$('customerForm')?.addEventListener('submit',event=>{event.preventDefault();if(!validateCustomer())return;window.open(whatsappURL(enquiryMessage(customer(),reference())),'_blank','noopener,noreferrer');});
$('printEnquiry')?.addEventListener('click',printEnquiry);
window.addEventListener('storage',event=>{if(event.key==='madhan_cart'||event.key===null){cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',[])));updateCart();}if(event.key==='madhan_wishlist'||event.key===null){favorites=loadFavorites();renderProducts();updateFavorites();}if(event.key==='madhan_dark'||event.key===null)setTheme(read('madhan_dark',false));});
window.addEventListener('pageshow',()=>{cart=normalizeCart(read('madhan_cart',read('yuvaraj_cart',cart)));updateCart();});
const currentPage = location.pathname.split('/').pop() || 'index.html';
document.querySelectorAll('#navigation a,.mobile-dock a').forEach(link=>{
  const match=link.getAttribute('href')===(currentPage==='product.html'?'catalogue.html':currentPage);
  if(match)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');
});
